---
label: default
hide_body: true
is_partial: false
fields:
- type: text
  name: title
  label: Title
  config:
    required: true
- type: textarea
  name: description
  label: Description
  description: A short description of the page
  config:
    required: true
- type: datetime
  name: publish_date
  label: Publish Date
  config:
    required: true
- type: field_group
  name: author
  label: Author
  description: Details about the author of the article.
  fields:
  - type: text
    name: author_name
    label: Author Name
    description: The name of the author of the article.
  - type: text
    name: author_title
    label: Author Job Title
    description: The job title of the author of the article.
- type: text
  name: layout
  label: layout
  hidden: true
  default: post
- type: text
  name: author_name
  label: Author Name
  description: The name of the author of the article.
  default: Buiewbciewbc
