---
label: project
hide_body: false
is_partial: false
fields:
- type: select
  config:
    source:
      type: simple
    options:
    - Credit Report
    - Credit Cards
    - Loans
    - Mortgages
    required: true
  label: Category
  name: category
  description: The category the article falls into.
  default: Credit Report
- type: text
  name: title
  label: Title
- name: sub_heading
  label: Sub Heading
  type: text
  hidden: false
  default: ''
- name: banner_image
  label: Banner Image
  type: file
  description: Dimensions work best at 1200 pixels by 400 pixels
  hidden: false
  default: ''
- type: field_group
  name: author
  label: Author
  description: Details about the author of the article.
  fields:
  - type: text
    name: name
    label: Author Name
    description: The name of the author of the article.
    default: Hellp
  - type: text
    name: title
    label: Author Job Title
    description: The job title of the author of the article.
    default: erferverver
  - type: file
    name: image
    label: Author Image
    description: An image of the author of the article.
- name: tags
  label: Tags
  type: tag_list
  hidden: false
  default: []
- name: slug
  label: Slug
  type: text
  hidden: false
  default: ''
pages:
- _projects/hvuih.md
- _projects/ccjs-whats-going-on.md
- _projects/olassss.md
- _projects/hello-world.md
- _credit-cards/new-project-1.md
- _projects/somewhere-to-live-maybe.html
